from datetime import datetime, timedelta
from data.database import get_weekly_stats


def get_all_users_with_activity():
    import sqlite3
    import os
    from data.database import DB_PATH
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute("""
        SELECT DISTINCT user_id 
        FROM journal 
        WHERE created_at >= datetime('now', '-7 days')
    """)
    
    users = [row[0] for row in cursor.fetchall()]
    conn.close()
    return users


def generate_weekly_summary(user_id: int) -> str:
    stats = get_weekly_stats(user_id)
    
    if not stats:
        return None
    
    total = sum(s[0] for s in stats)
    bullish = sum(s[1] for s in stats)
    bearish = sum(s[2] for s in stats)
    
    lines = [
        "📊 *Weekly Report - Crypto TA Bot*\n",
        f"📅 Periode: {(datetime.now() - timedelta(days=7)).strftime('%d %b')} - {datetime.now().strftime('%d %b %Y')}\n",
        "━━━━━━━━━━━━━━━━━━━━",
        f"📈 *Total Analisis:* {total}",
        f"🟢 Bullish: {bullish}",
        f"🔴 Bearish: {bearish}",
        "",
        "📊 *Top Pasangan:*",
    ]
    
    for total, bullish, bearish, pair, count in stats[:5]:
        lines.append(f"  • {pair}: {count}x")
    
    trend = "📈 Bullish" if bullish > bearish else "📉 Bearish" if bearish > bullish else "➡ Sideways"
    lines.extend(["", f"💡 *Trend:* {trend}", "", "_Generated by Crypto TA Bot_"])
    
    return "\n".join(lines)


def run_weekly_report():
    print(f"[{datetime.now()}] Generating weekly reports...")
    
    users = get_all_users_with_activity()
    print(f"Found {len(users)} active users")
    
    for user_id in users:
        try:
            report = generate_weekly_summary(user_id)
            if report:
                print(f"Generated report for user {user_id}")
        except Exception as e:
            print(f"Error generating report for {user_id}: {e}")
    
    print(f"[{datetime.now()}] Weekly reports complete")


if __name__ == "__main__":
    run_weekly_report()