import os
import io
from datetime import datetime
from fpdf import FPDF


class AnalysisPDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 15)
        self.cell(0, 10, 'Analisis Teknikal Crypto', border=False, align='C')
        self.ln(5)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Generated by Crypto TA Bot - {datetime.now().strftime("%Y-%m-%d")}', align='C')


def generate_pdf(analysis_text: str, pair: str = None, timeframe: str = None, signal: str = None) -> io.BytesIO:
    pdf = AnalysisPDF()
    pdf.add_page()
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, f'Pair: {pair or "Unknown"} | Timeframe: {timeframe or "Unknown"}', ln=True)
    if signal:
        pdf.cell(0, 10, f'Signal: {signal}', ln=True)
    pdf.ln(5)
    
    pdf.set_font('helvetica', '', 10)
    
    lines = analysis_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
        
        if line.startswith('**') and line.endswith('**'):
            pdf.set_font('helvetica', 'B', 11)
            pdf.cell(0, 5, line.replace('*', ''), ln=True)
            pdf.ln(2)
        elif line.startswith('**'):
            pdf.set_font('helvetica', 'B', 10)
            pdf.cell(0, 5, line.replace('*', ''), ln=True)
        elif '•' in line or line.startswith('-'):
            pdf.set_font('helvetica', '', 10)
            pdf.set_x(10)
            pdf.cell(0, 5, line.replace('•', '').replace('-', '').strip(), ln=True)
        else:
            pdf.set_font('helvetica', '', 10)
            pdf.cell(0, 5, line.replace('*', '').replace('_', ''), ln=True)
    
    pdf.ln(10)
    pdf.set_font('helvetica', 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: Analisis ini bersifat edukatif dan bukan merupakan saran finansial. Selalu lakukan riset mandiri (DYOR).")
    
    return io.BytesIO(pdf.output(dest='S').encode('latin-1', errors='replace'))


def generate_pdf_file(analysis_text: str, pair: str = None, timeframe: str = None, signal: str = None) -> str:
    pdf = AnalysisPDF()
    pdf.add_page()
    
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, f'Pair: {pair or "Unknown"} | Timeframe: {timeframe or "Unknown"}', ln=True)
    if signal:
        pdf.cell(0, 10, f'Signal: {signal}', ln=True)
    pdf.ln(5)
    
    pdf.set_font('helvetica', '', 10)
    lines = analysis_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
        
        try:
            clean_line = line.replace('*', '').replace('_', '').encode('latin-1', errors='replace').decode('latin-1')
            pdf.multi_cell(0, 5, clean_line)
        except Exception as e:
            pdf.ln(1)
    
    pdf.ln(10)
    pdf.set_font('helvetica', 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: Analisis ini bersifat edukatif dan bukan merupakan saran finansial.")
    
    filename = f"analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    try:
        pdf.output(filename)
    except Exception as e:
        filename = f"analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(analysis_text)
    return filename